export interface RecommendationCandidate {
  id: string;
  title: string;
  tags: string[];
  personaFit: Array<'PERSONAL' | 'BUSINESS'>;
  minTier: 0 | 1 | 2;
  effort: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  nextStepTemplate: string;
}

export const RECOMMENDATION_CATALOG_SEED: RecommendationCandidate[] = [
  {
    id: 'personal-stack-audit',
    title: 'Personal Stack Audit Sprint',
    tags: ['stack', 'architecture', 'nextjs', 'supabase'],
    personaFit: ['PERSONAL'],
    minTier: 0,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Audit your current stack against {goal} and list top 3 bottlenecks.',
  },
  {
    id: 'personal-10day-plan',
    title: '10-Day Build Plan',
    tags: ['build', 'launch', 'mvp', 'deployment'],
    personaFit: ['PERSONAL'],
    minTier: 0,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Generate a 10-day roadmap for {goal} with daily milestones.',
  },
  {
    id: 'personal-terminal-mastery',
    title: 'Terminal Command Mastery Track',
    tags: ['terminal', 'workflow', 'automation'],
    personaFit: ['PERSONAL'],
    minTier: 0,
    effort: 'medium',
    impact: 'medium',
    nextStepTemplate: 'Run a daily command drill aligned to {goal} and measure cycle-time reduction.',
  },
  {
    id: 'personal-feature-shipping-loop',
    title: 'Feature Shipping Loop',
    tags: ['feature', 'delivery', 'quality'],
    personaFit: ['PERSONAL'],
    minTier: 1,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Implement one production feature tied to {goal} with test + deploy checklist.',
  },
  {
    id: 'personal-debug-doctrine',
    title: 'Debug Doctrine: 15-Min Triage',
    tags: ['debug', 'errors', 'observability', 'latency'],
    personaFit: ['PERSONAL'],
    minTier: 1,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Adopt requestId-first triage for {goal}; capture provider chain per failure.',
  },
  {
    id: 'personal-gpu-ui-optimization',
    title: 'GPU UI Optimization Pass',
    tags: ['performance', 'gpu', 'animation', 'ux'],
    personaFit: ['PERSONAL'],
    minTier: 1,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Optimize transform/opacity animations in the {goal} flow and re-measure frame drops.',
  },
  {
    id: 'business-funnel-triage',
    title: 'Conversion Funnel Triage',
    tags: ['funnel', 'growth', 'conversion', 'waitlist'],
    personaFit: ['BUSINESS'],
    minTier: 0,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Map drop-offs in {goal} funnel and patch highest-loss step first.',
  },
  {
    id: 'business-revenue-ops',
    title: 'Revenue Ops Blueprint',
    tags: ['revenue', 'pricing', 'sales'],
    personaFit: ['BUSINESS'],
    minTier: 0,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Define pricing-to-outcome narrative for {goal} and publish one-page offer brief.',
  },
  {
    id: 'business-architecture-governance',
    title: 'Architecture Governance Board',
    tags: ['architecture', 'governance', 'risk'],
    personaFit: ['BUSINESS'],
    minTier: 1,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Create decision gates for {goal}: security, performance, rollout, rollback.',
  },
  {
    id: 'business-swarm-orchestration',
    title: 'Agent Swarm Orchestration',
    tags: ['orchestration', 'agents', 'automation'],
    personaFit: ['BUSINESS'],
    minTier: 1,
    effort: 'high',
    impact: 'high',
    nextStepTemplate: 'Assign specialized agents to deliver {goal} with explicit ownership and SLAs.',
  },
  {
    id: 'business-error-budget',
    title: 'Error Budget + Incident Playbook',
    tags: ['reliability', 'incident', 'observability'],
    personaFit: ['BUSINESS'],
    minTier: 1,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Set error budget for {goal}, define on-call protocol, and enforce postmortem template.',
  },
  {
    id: 'business-platform-kpi',
    title: 'Platform KPI Command Center',
    tags: ['kpi', 'analytics', 'dashboard'],
    personaFit: ['BUSINESS'],
    minTier: 1,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Instrument top 5 KPIs for {goal} and set weekly review cadence.',
  },
  {
    id: 'universal-api-contract',
    title: 'Unified API Contract Enforcement',
    tags: ['api', 'contract', 'schema', 'architecture'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 0,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Standardize request/response contract for {goal} across all AI endpoints.',
  },
  {
    id: 'universal-state-machine-lock',
    title: 'State Machine Lockdown',
    tags: ['state', 'journey', 'validation'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 0,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Enforce deterministic transitions for {goal}; block invalid state jumps.',
  },
  {
    id: 'universal-provider-debug',
    title: 'Provider Fallback Telemetry',
    tags: ['provider', 'debug', 'telemetry', 'latency'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 0,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Capture requested->attempted->selected provider chain for {goal} on every request.',
  },
  {
    id: 'universal-customer-first-copy',
    title: 'Customer-First Copy Optimization',
    tags: ['copy', 'ux', 'onboarding', 'learning'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 0,
    effort: 'low',
    impact: 'medium',
    nextStepTemplate: 'Rewrite first response for {goal}: clear result-first answer, one next action.',
  },
  {
    id: 'universal-lesson-recommender',
    title: 'Adaptive Lesson Recommender',
    tags: ['learning', 'recommendation', 'curriculum'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 1,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Recommend the next module for {goal} using persona + difficulty + progress.',
  },
  {
    id: 'universal-release-safety',
    title: 'Golden Release Safety Gate',
    tags: ['release', 'deploy', 'backup', 'quality'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 0,
    effort: 'low',
    impact: 'high',
    nextStepTemplate: 'Apply full release gate for {goal}: typecheck, build, parity, ZIP backup, smoke.',
  },
  {
    id: 'tier2-strategic-automation',
    title: 'Tier-2 Strategic Automation Suite',
    tags: ['automation', 'strategy', 'scale'],
    personaFit: ['BUSINESS'],
    minTier: 2,
    effort: 'high',
    impact: 'high',
    nextStepTemplate: 'Deploy strategic automation loops for {goal} with KPI-linked decision triggers.',
  },
  {
    id: 'tier2-founder-playbook',
    title: 'Founder Operating Playbook',
    tags: ['founder', 'operations', 'execution'],
    personaFit: ['PERSONAL', 'BUSINESS'],
    minTier: 2,
    effort: 'medium',
    impact: 'high',
    nextStepTemplate: 'Run weekly operating cadence for {goal} with risk review and execution scoreboard.',
  },
];
